import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>ecommerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<h1 className='text-3xl font-bold '>Shop Africa</h1>
      
</div>
  )
}
